### ISSUE TITLE
Mistakes in README

### ISSUE THREAD

**Issue by nik6ena** [Michaelangel007/crc32#4]
|Polynomial| Binary                                |
|---------:|--------------------------------------:|
|0x04C11DB7| `00000100_11000001_00011101_10110111` |
|0xEDB88320| `11101101-10111000_10000011_00100000` |

I think this hyphen is a mistake and should be changed to an underscore, or better, let separator be a space. `11101101 10111000 10000011 00100000`. That hyphen almost confused me.

Also in the section "CRC32 Implementation",
Inverting the bits should be `~1` (0xFFFFFFFF) and not -1.

**Comment by Michaelangel007** [comment]
Thanks for the catch! Fixed.
