### ISSUE TITLE
Add 123456789-check values to table of all 32 permutations

### ISSUE THREAD

**Issue by RalphCorderoy** [Michaelangel007/crc32#7]
The table at https://github.com/Michaelangel007/crc32/blob/master/README.md?plain=1#L568 would benefit from a column for the CRC32 that the row produces for the traditional check value of the nine ASCII digits `123456789`.

**Comment by Michaelangel007** [comment]
Sorry the late reply.

Great idea!

**Comment by Michaelangel007** [comment]
Done.  Thanks again for the feedback.
